### ISSUE TITLE
Don't require virtualbox

### ISSUE THREAD

**Issue by Inkbug** [p2pu/lernanta-dev-env#2]
I'd like to run and help develop lernanta, but the requirement of running a virtual os are stopping me. I don't have the resources on my laptop to do so. I t would be nice to be able to just install it without anything special on windows.

**Comment by mkcode** [comment]
Unfortunately, virtualbox is required for the creation of the VM. No way to get around it. The vm system only requires about 256 RAM for it and CPU only when it's being so it should run OK on a modest system

**Comment by dirkcuys** [comment]
@Inkbug if you can't run a virtual machine, you can still set up the development environment the old way: https://github.com/p2pu/lernanta/wiki/Setup-Lernanta-Manually

**Comment by Inkbug** [comment]
@dirkcuys Hi! I've switched to Linux so I'm fine now :smile:
